### PR TITLE
Release 2.1.3

### PR DESCRIPTION
**Pull request by lartist**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Merge dev into master
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @lartist 

I have checked your PR with PS1788. When I installed the module `ps_languageselector` it does not display on FO when the user is logged In and Out

- uninstall the current module
- under modules > git clone `git@github.com:PrestaShop/ps_languageselector.git`
- cd ps_languageselector > git pull --rebase origin dev
- git prc origin 37 dev
- composer install

image

https://user-images.githubusercontent.com/92912932/225606320-a2fb733e-199d-4d9b-b55d-7340a2b61406.mp4

Could you please check it ? Did i miss something ?

Thank You!

**Comment by Hlavtox** [comment]
@HanaRebaiQA We don't know anything from your report, you need to provide more information.

Do you have more than 1 active language?
Do you have the module hooked in a proper hook after reinstalling it?

It's not caused by this PR anyway. 🤷‍♂️

**Review by kpodemski — APPROVED** [review]
This module is a widget that does not hook anywhere. If you uninstall and install it again, it will only show if you reset your theme. If we want to do it this way, it's another issue to create.

Also, can we please stop testing PRs where there's one word removed? What's the point @Robin-Fischer-PS @hibatallahAouadni ?

**Comment by Hlavtox** [comment]
@kpodemski You must understand, it's the process (the company pays for). 😄

**Pull request merged**
